version: '3'
services:

  nginx:
    build: ./nginx/
    container_name: nginx-container
    ports:
      - 80:80
    links:
      - php
    volumes:
      - ./www/html/login_form/:/var/www/html/

  php:
    image: php:8.0-fpm
    container_name: php-container
    expose:
      - 9000
    volumes:
      - ./www/html/login_form/:/var/www/html/

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    restart: ${RESTART_MODE}
#    ports:
#      - "8001:80"
#    environment:
#      - PMA_ARBITRARY=0
#      - PMA_HOSTS=mysql
#    depends_on:
#      - mysql
#
#
#  mysql:
#    image: mysql:5.7
#    container_name: mysql
#    restart: unless-stopped
#    command: --default-authentication-plugin=mysql_native_password
#    command: --innodb_use_native_aio=0
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./data/mysql:/var/lib/mysql
#    # пароль для root пользователя
#    environment:
#      MYSQL_ROOT_PASSWORD: secret